export const packageBasic = [
  {
    name: "Paquete 1",
    price: 350,
    note_price: "Branding",
    package_items: [
      { value: "-", item_id: 1 },
      { value: "-", item_id: 2 },
      { value: "-", item_id: 3 },
      { value: "-", item_id: 4 },
      { value: "-", item_id: 5 },
      { value: "Si", item_id: 6 },
      { value: "Si", item_id: 7 },
      { value: "No", item_id: 8 },
      { value: "Si", item_id: 9 },
      { value: "No", item_id: 10 },
      { value: "Si", item_id: 11 },
      { value: "-", item_id: 12 },
      { value: "-", item_id: 13 },
      { value: "-", item_id: 14 },
      { value: "-", item_id: 15 },
      { value: "-", item_id: 16 },
      { value: "-", item_id: 17 },
      { value: "-", item_id: 18 },
      { value: "-", item_id: 19 },
      { value: "-", item_id: 20 },
      { value: "-", item_id: 21 },
      { value: "-", item_id: 22 },
      {
        value: "-",
        item_id: 23,
      },
      { value: "-", item_id: 24 },
      { value: "-", item_id: 25 },
      { value: "-", item_id: 26 },
      { value: "-", item_id: 27 },
      { value: "-", item_id: 28 },
      { value: "-", item_id: 29 },
      { value: "-", item_id: 30 },
      { value: "-", item_id: 31 },
      { value: "-", item_id: 32 },
      { value: "-", item_id: 33 },
      { value: "-", item_id: 34 },
      { value: "-", item_id: 35 },
      { value: "-", item_id: 36 },
      { value: "-", item_id: 37 },
      { value: "-", item_id: 38 },
      { value: "-", item_id: 39 },
      { value: "-", item_id: 40 },
      { value: "-", item_id: 41 },
      { value: "-", item_id: 42 },
      { value: "-", item_id: 43 },
      { value: "-", item_id: 44 },
      { value: "-", item_id: 45 },
      { value: "-", item_id: 46 },
      { value: "-", item_id: 47 },
      { value: "-", item_id: 48 },
      { value: "-", item_id: 49 },
      { value: "-", item_id: 50 },
      { value: "-", item_id: 51 },
      { value: "-", item_id: 52 },
      { value: "-", item_id: 53 },
      { value: "-", item_id: 54 },
      { value: "-", item_id: 55 },
      { value: "-", item_id: 56 },
      { value: "-", item_id: 57 },
      { value: "-", item_id: 58 },
    ],
  },

  {
    name: "Paquete 2",
    price: 350,
    note_price: "Publicidad",
    package_items: [
      { value: "-", item_id: 1 },
      { value: "-", item_id: 2 },
      { value: "-", item_id: 3 },
      { value: "-", item_id: 4 },
      { value: "-", item_id: 5 },
      { value: "-", item_id: 6 },
      { value: "-", item_id: 7 },
      { value: "-", item_id: 8 },
      { value: "Si", item_id: 9 },
      { value: "-", item_id: 10 },
      { value: "-", item_id: 11 },
      { value: "-", item_id: 12 },
      { value: "-", item_id: 13 },
      { value: "-", item_id: 14 },
      { value: "-", item_id: 15 },
      { value: "-", item_id: 16 },
      { value: "-", item_id: 17 },
      { value: "-", item_id: 18 },
      { value: "-", item_id: 19 },
      { value: "-", item_id: 20 },
      { value: "-", item_id: 21 },
      { value: "1 videos de max 30 seg.", item_id: 22 },
      {
        value: "Si(Todos los recursos entrega el cliente virtualmente)",
        item_id: 23,
      },
      { value: "Vertical", item_id: 24 },
      { value: "Si", item_id: 25 },
      { value: "Si", item_id: 26 },
      { value: "No", item_id: 27 },
      { value: "No", item_id: 28 },
      { value: "Si", item_id: 29 },
      { value: "Imagen - Carrusel - Video", item_id: 30 },
      { value: "Si", item_id: 31 },
      { value: "Facebook - IG", item_id: 32 },
      { value: "2", item_id: 33 },
      { value: "-", item_id: 34 },
      { value: "-", item_id: 35 },
      { value: "-", item_id: 36 },
      { value: "-", item_id: 37 },
      { value: "-", item_id: 38 },
      { value: "-", item_id: 39 },
      { value: "-", item_id: 40 },
      { value: "-", item_id: 41 },
      { value: "-", item_id: 42 },
      { value: "-", item_id: 43 },
      { value: "-", item_id: 44 },
      { value: "-", item_id: 45 },
      { value: "-", item_id: 46 },
      { value: "-", item_id: 47 },
      { value: "-", item_id: 48 },
      { value: "-", item_id: 49 },
      { value: "-", item_id: 50 },
      { value: "-", item_id: 51 },
      { value: "-", item_id: 52 },
      { value: "-", item_id: 53 },
      { value: "-", item_id: 54 },
      { value: "-", item_id: 55 },
      { value: "-", item_id: 56 },
      { value: "-", item_id: 57 },
      { value: "-", item_id: 58 },
    ],
  },
  {
    name: "Paquete 3",
    price: 600,
    note_price: "Gestion de redes",
    package_items: [
      { value: "-", item_id: 1 },
      { value: "-", item_id: 2 },
      { value: "-", item_id: 3 },
      { value: "-", item_id: 4 },
      { value: "-", item_id: 5 },
      { value: "Si", item_id: 6 },
      { value: "Si", item_id: 7 },
      { value: "No", item_id: 8 },
      { value: "Si", item_id: 9 },
      { value: "No", item_id: 10 },
      { value: "Si", item_id: 11 },
      { value: "Si", item_id: 12 },
      { value: "8 publicaciones", item_id: 13 },
      { value: "Imagen - Carrusel", item_id: 14 },
      { value: "Facebook - IG - Tiktok", item_id: 15 },
      { value: "Si", item_id: 16 },
      { value: "Si", item_id: 17 },
      { value: "Si", item_id: 18 },
      { value: "Si", item_id: 19 },
      { value: "Si", item_id: 20 },
      { value: "Si", item_id: 21 },
      { value: "1 videos de max 30 seg.", item_id: 22 },
      {
        value: "Si(Todos los recursos entrega el cliente virtualmente)",
        item_id: 23,
      },
      { value: "Vertical", item_id: 24 },
      { value: "Si", item_id: 25 },
      { value: "Si", item_id: 26 },
      { value: "No", item_id: 27 },
      { value: "No", item_id: 28 },
      { value: "Si", item_id: 29 },
      { value: "Imagen - Carrusel - Video", item_id: 30 },
      { value: "Si", item_id: 31 },
      { value: "Facebook - IG", item_id: 32 },
      { value: "2", item_id: 33 },
      { value: "-", item_id: 34 },
      { value: "-", item_id: 35 },
      { value: "-", item_id: 36 },
      { value: "-", item_id: 37 },
      { value: "-", item_id: 38 },
      { value: "-", item_id: 39 },
      { value: "-", item_id: 40 },
      { value: "-", item_id: 41 },
      { value: "-", item_id: 42 },
      { value: "-", item_id: 43 },
      { value: "-", item_id: 44 },
      { value: "-", item_id: 45 },
      { value: "-", item_id: 46 },
      { value: "-", item_id: 47 },
      { value: "-", item_id: 48 },
      { value: "-", item_id: 49 },
      { value: "-", item_id: 50 },
      { value: "-", item_id: 51 },
      { value: "-", item_id: 52 },
      { value: "-", item_id: 53 },
      { value: "-", item_id: 54 },
      { value: "-", item_id: 55 },
      { value: "-", item_id: 56 },
      { value: "-", item_id: 57 },
      { value: "-", item_id: 58 },
    ],
  },
];

export const packageIntermediate = [
  {
    name: "Paquete 1",
    price: 750,
    note_price: "Gestion de Redes",
    package_items: [
      { value: "-", item_id: 1 },
      { value: "-", item_id: 2 },
      { value: "-", item_id: 3 },
      { value: "-", item_id: 4 },
      { value: "-", item_id: 5 },
      { value: "Si", item_id: 6 },
      { value: "Si", item_id: 7 },
      { value: "No", item_id: 8 },
      { value: "Si", item_id: 9 },
      { value: "No", item_id: 10 },
      { value: "Si", item_id: 11 },
      { value: "Si", item_id: 12 },
      { value: "8 publicaciones", item_id: 13 },
      { value: "Imagen - Carrusel", item_id: 14 },
      { value: "Facebook - IG - Tiktok", item_id: 15 },
      { value: "Si", item_id: 16 },
      { value: "Si", item_id: 17 },
      { value: "Si", item_id: 18 },
      { value: "Si", item_id: 19 },
      { value: "Si", item_id: 20 },
      { value: "Si", item_id: 21 },
      { value: "4 videos de max 30 seg.", item_id: 22 },
      {
        value: "Si(Todos los recursos entrega el cliente virtualmente)",
        item_id: 23,
      },
      { value: "Vertical", item_id: 24 },
      { value: "Si", item_id: 25 },
      { value: "Si", item_id: 26 },
      { value: "No", item_id: 27 },
      { value: "No", item_id: 28 },
      { value: "Si", item_id: 29 },
      { value: "Imagen - Carrusel - Video", item_id: 30 },
      { value: "Si", item_id: 31 },
      { value: "Facebook - IG", item_id: 32 },
      { value: "2", item_id: 33 },
      { value: "Si", item_id: 34 },
      { value: "5 productos max.", item_id: 35 },
      { value: "Si", item_id: 36 },
      { value: "-", item_id: 37 },
      { value: "-", item_id: 38 },
      { value: "-", item_id: 39 },
      { value: "-", item_id: 40 },
      { value: "-", item_id: 41 },
      { value: "-", item_id: 42 },
      { value: "-", item_id: 43 },
      { value: "-", item_id: 44 },
      { value: "-", item_id: 45 },
      { value: "-", item_id: 46 },
      { value: "-", item_id: 47 },
      { value: "-", item_id: 48 },
      { value: "-", item_id: 49 },
      { value: "-", item_id: 50 },
      { value: "-", item_id: 51 },
      { value: "-", item_id: 52 },
      { value: "-", item_id: 53 },
      { value: "-", item_id: 54 },
      { value: "-", item_id: 55 },
      { value: "-", item_id: 56 },
      { value: "-", item_id: 57 },
      { value: "-", item_id: 58 },
    ],
  },
  {
    name: "Paquete 2",
    price: 950,
    note_price: "Gestion + web on page",
    package_items: [
      { value: "-", item_id: 1 },
      { value: "-", item_id: 2 },
      { value: "-", item_id: 3 },
      { value: "-", item_id: 4 },
      { value: "-", item_id: 5 },
      { value: "Si", item_id: 6 },
      { value: "Si", item_id: 7 },
      { value: "No", item_id: 8 },
      { value: "Si", item_id: 9 },
      { value: "No", item_id: 10 },
      { value: "Si", item_id: 11 },
      { value: "Si", item_id: 12 },
      { value: "8 publicaciones", item_id: 13 },
      { value: "Imagen - Carrusel", item_id: 14 },
      { value: "Facebook - IG - Tiktok - Google maps", item_id: 15 },
      { value: "Si", item_id: 16 },
      { value: "Si", item_id: 17 },
      { value: "Si", item_id: 18 },
      { value: "Si", item_id: 19 },
      { value: "Si", item_id: 20 },
      { value: "Si", item_id: 21 },
      { value: "4 videos de max 30 seg.", item_id: 22 },
      {
        value: "Si(Todos los recursos entrega el cliente virtualmente)",
        item_id: 23,
      },
      { value: "Vertical", item_id: 24 },
      { value: "Si", item_id: 25 },
      { value: "Si", item_id: 26 },
      { value: "No", item_id: 27 },
      { value: "No", item_id: 28 },
      { value: "Si", item_id: 29 },
      { value: "Imagen - Carrusel - Video", item_id: 30 },
      { value: "Si", item_id: 31 },
      { value: "Facebook - IG", item_id: 32 },
      { value: "2", item_id: 33 },
      { value: "Si", item_id: 34 },
      { value: "8 productos max.", item_id: 35 },
      { value: "Si", item_id: 36 },
      { value: "-", item_id: 37 },
      { value: "-", item_id: 38 },
      { value: "-", item_id: 39 },
      { value: "On Page", item_id: 40 },
      { value: "Estandar", item_id: 41 },
      { value: "No", item_id: 42 },
      { value: "Si", item_id: 43 },
      { value: "No", item_id: 44 },
      { value: "-", item_id: 45 },
      { value: "-", item_id: 46 },
      { value: "-", item_id: 47 },
      { value: "-", item_id: 48 },
      { value: "-", item_id: 49 },
      { value: "-", item_id: 50 },
      { value: "-", item_id: 51 },
      { value: "-", item_id: 52 },
      { value: "-", item_id: 53 },
      { value: "-", item_id: 54 },
      { value: "-", item_id: 55 },
      { value: "-", item_id: 56 },
      { value: "-", item_id: 57 },
      { value: "-", item_id: 58 },
    ],
  },
  {
    name: "Paquete 3",
    price: 1200,
    note_price: "Estrategia + gestion + web on page",
    package_items: [
      { value: "Diseño", item_id: 1 },
      { value: "Si", item_id: 2 },
      { value: "Si", item_id: 3 },
      { value: "Si", item_id: 4 },
      { value: "Si", item_id: 5 },
      { value: "Si", item_id: 6 },
      { value: "Si", item_id: 7 },
      { value: "No", item_id: 8 },
      { value: "Si", item_id: 9 },
      { value: "No", item_id: 10 },
      { value: "Si", item_id: 11 },
      { value: "Si", item_id: 12 },
      { value: "8 publicaciones", item_id: 13 },
      { value: "Imagen - Carrusel", item_id: 14 },
      { value: "Facebook - IG - Tiktok - Google maps", item_id: 15 },
      { value: "Si", item_id: 16 },
      { value: "Si", item_id: 17 },
      { value: "Si", item_id: 18 },
      { value: "Si", item_id: 19 },
      { value: "Si", item_id: 20 },
      { value: "Si", item_id: 21 },
      { value: "6 videos de max 30 seg.", item_id: 22 },
      {
        value: "Si(Todos los recursos entrega el cliente virtualmente)",
        item_id: 23,
      },
      { value: "Vertical", item_id: 24 },
      { value: "Si", item_id: 25 },
      { value: "Si", item_id: 26 },
      { value: "Si", item_id: 27 },
      { value: "4", item_id: 28 },
      { value: "Si", item_id: 29 },
      { value: "Imagen - Carrusel - Video", item_id: 30 },
      { value: "Si", item_id: 31 },
      { value: "Facebook - IG", item_id: 32 },
      { value: "2", item_id: 33 },
      { value: "Si", item_id: 34 },
      { value: "10 productos max.", item_id: 35 },
      { value: "Si", item_id: 36 },
      { value: "Si", item_id: 37 },
      { value: "Lunes a Viernes 9 - 5 pm", item_id: 38 },
      { value: "Si", item_id: 39 },
      { value: "Multipage", item_id: 40 },
      { value: "Personalizado", item_id: 41 },
      { value: "Si Max. 10", item_id: 42 },
      { value: "Si", item_id: 43 },
      { value: "Si", item_id: 44 },
      { value: "-", item_id: 45 },
      { value: "-", item_id: 46 },
      { value: "-", item_id: 47 },
      { value: "-", item_id: 48 },
      { value: "-", item_id: 49 },
      { value: "-", item_id: 50 },
      { value: "-", item_id: 51 },
      { value: "-", item_id: 52 },
      { value: "-", item_id: 53 },
      { value: "-", item_id: 54 },
      { value: "-", item_id: 55 },
      { value: "-", item_id: 56 },
      { value: "-", item_id: 57 },
      { value: "-", item_id: 58 },
    ],
  },
];

export const packageAdvanced = [
  {
    name: "Paquete 1",
    price: 1200,
    note_price: "Estrategia + gestion + web on page",
    package_items: [
      { value: "-", item_id: 1 },
      { value: "-", item_id: 2 },
      { value: "-", item_id: 3 },
      { value: "-", item_id: 4 },
      { value: "-", item_id: 5 },
      { value: "-", item_id: 6 },
      { value: "-", item_id: 7 },
      { value: "-", item_id: 8 },
      { value: "-", item_id: 9 },
      { value: "-", item_id: 10 },
      { value: "-", item_id: 11 },
      { value: "-", item_id: 12 },
      { value: "-", item_id: 13 },
      { value: "-", item_id: 14 },
      { value: "-", item_id: 15 },
      { value: "-", item_id: 16 },
      { value: "-", item_id: 17 },
      { value: "-", item_id: 18 },
      { value: "-", item_id: 19 },
      { value: "-", item_id: 20 },
      { value: "-", item_id: 21 },
      { value: "-", item_id: 22 },
      { value: "-", item_id: 23 },
      { value: "-", item_id: 24 },
      { value: "-", item_id: 25 },
      { value: "-", item_id: 26 },
      { value: "-", item_id: 27 },
      { value: "-", item_id: 28 },
      { value: "-", item_id: 29 },
      { value: "-", item_id: 30 },
      { value: "-", item_id: 31 },
      { value: "-", item_id: 32 },
      { value: "-", item_id: 33 },
      { value: "-", item_id: 34 },
      { value: "-", item_id: 35 },
      { value: "-", item_id: 36 },
      { value: "-", item_id: 37 },
      { value: "-", item_id: 38 },
      { value: "-", item_id: 39 },
      { value: "-", item_id: 40 },
      { value: "-", item_id: 41 },
      { value: "-", item_id: 42 },
      { value: "-", item_id: 43 },
      { value: "-", item_id: 44 },
      { value: "-", item_id: 45 },
      { value: "-", item_id: 46 },
      { value: "-", item_id: 47 },
      { value: "-", item_id: 48 },
      { value: "-", item_id: 49 },
      { value: "-", item_id: 50 },
      { value: "-", item_id: 51 },
      { value: "-", item_id: 52 },
      { value: "-", item_id: 53 },
      { value: "-", item_id: 54 },
      { value: "-", item_id: 55 },
      { value: "-", item_id: 56 },
      { value: "-", item_id: 57 },
      { value: "-", item_id: 58 },
    ],
  },

  {
    name: "Paquete 2",
    price: 1300,
    note_price: "Gestion + web on page",
    package_items: [
      { value: "-", item_id: 1 },
      { value: "-", item_id: 2 },
      { value: "-", item_id: 3 },
      { value: "-", item_id: 4 },
      { value: "-", item_id: 5 },
      { value: "-", item_id: 6 },
      { value: "-", item_id: 7 },
      { value: "-", item_id: 8 },
      { value: "-", item_id: 9 },
      { value: "-", item_id: 10 },
      { value: "-", item_id: 11 },
      { value: "-", item_id: 12 },
      { value: "-", item_id: 13 },
      { value: "-", item_id: 14 },
      { value: "-", item_id: 15 },
      { value: "-", item_id: 16 },
      { value: "-", item_id: 17 },
      { value: "-", item_id: 18 },
      { value: "-", item_id: 19 },
      { value: "-", item_id: 20 },
      { value: "-", item_id: 21 },
      { value: "-", item_id: 22 },
      { value: "-", item_id: 23 },
      { value: "-", item_id: 24 },
      { value: "-", item_id: 25 },
      { value: "-", item_id: 26 },
      { value: "-", item_id: 27 },
      { value: "-", item_id: 28 },
      { value: "-", item_id: 29 },
      { value: "-", item_id: 30 },
      { value: "-", item_id: 31 },
      { value: "-", item_id: 32 },
      { value: "-", item_id: 33 },
      { value: "-", item_id: 34 },
      { value: "-", item_id: 35 },
      { value: "-", item_id: 36 },
      { value: "-", item_id: 37 },
      { value: "-", item_id: 38 },
      { value: "-", item_id: 39 },
      { value: "-", item_id: 40 },
      { value: "-", item_id: 41 },
      { value: "-", item_id: 42 },
      { value: "-", item_id: 43 },
      { value: "-", item_id: 44 },
      { value: "-", item_id: 45 },
      { value: "-", item_id: 46 },
      { value: "-", item_id: 47 },
      { value: "-", item_id: 48 },
      { value: "-", item_id: 49 },
      { value: "-", item_id: 50 },
      { value: "-", item_id: 51 },
      { value: "-", item_id: 52 },
      { value: "-", item_id: 53 },
      { value: "-", item_id: 54 },
      { value: "-", item_id: 55 },
      { value: "-", item_id: 56 },
      { value: "-", item_id: 57 },
      { value: "-", item_id: 58 },
    ],
  },
  {
    name: "Paquete 3",
    price: 1500,
    note_price: "Estrategia + gestion + web on page",
    package_items: [
      { value: "-", item_id: 1 },
      { value: "-", item_id: 2 },
      { value: "-", item_id: 3 },
      { value: "-", item_id: 4 },
      { value: "-", item_id: 5 },
      { value: "-", item_id: 6 },
      { value: "-", item_id: 7 },
      { value: "-", item_id: 8 },
      { value: "-", item_id: 9 },
      { value: "-", item_id: 10 },
      { value: "-", item_id: 11 },
      { value: "-", item_id: 12 },
      { value: "-", item_id: 13 },
      { value: "-", item_id: 14 },
      { value: "-", item_id: 15 },
      { value: "-", item_id: 16 },
      { value: "-", item_id: 17 },
      { value: "-", item_id: 18 },
      { value: "-", item_id: 19 },
      { value: "-", item_id: 20 },
      { value: "-", item_id: 21 },
      { value: "-", item_id: 22 },
      { value: "-", item_id: 23 },
      { value: "-", item_id: 24 },
      { value: "-", item_id: 25 },
      { value: "-", item_id: 26 },
      { value: "-", item_id: 27 },
      { value: "-", item_id: 28 },
      { value: "-", item_id: 29 },
      { value: "-", item_id: 30 },
      { value: "-", item_id: 31 },
      { value: "-", item_id: 32 },
      { value: "-", item_id: 33 },
      { value: "-", item_id: 34 },
      { value: "-", item_id: 35 },
      { value: "-", item_id: 36 },
      { value: "-", item_id: 37 },
      { value: "-", item_id: 38 },
      { value: "-", item_id: 39 },
      { value: "-", item_id: 40 },
      { value: "-", item_id: 41 },
      { value: "-", item_id: 42 },
      { value: "-", item_id: 43 },
      { value: "-", item_id: 44 },
      { value: "-", item_id: 45 },
      { value: "-", item_id: 46 },
      { value: "-", item_id: 47 },
      { value: "-", item_id: 48 },
      { value: "-", item_id: 49 },
      { value: "-", item_id: 50 },
      { value: "-", item_id: 51 },
      { value: "-", item_id: 52 },
      { value: "-", item_id: 53 },
      { value: "-", item_id: 54 },
      { value: "-", item_id: 55 },
      { value: "-", item_id: 56 },
      { value: "-", item_id: 57 },
      { value: "-", item_id: 58 },
    ],
  },
];
